Repository HelixNetwork/pendulum-sdk, pull requests merged in 2019-10, with the labels that each got.

#52 lerna: 1.0.0-alpha.8
  lerna.json
  package-lock.json
  package.json
  packages/core/package.json
  packages/multisig/package.json
Labels: Fix, enhancement

#51 Dependency Updates and App Name Fix
  package-lock.json
  package.json
  packages/core/package-lock.json
  packages/core/test/integration/nocks/getNodeInfo.ts
  packages/http-client/package-lock.json
  packages/ipfs/package-lock.json
  packages/multisig/package-lock.json
  packages/pow/package-lock.json
  packages/rsa/package-lock.json
  packages/schnorr/package-lock.json
  packages/sha3/package-lock.json
  packages/unit-converter/package-lock.json
  packages/winternitz/package-lock.json
Labels: Fix, dependencies

#53 Added basic travis-ci build script
  .travis.yml
  README.md
Labels: CI
